insert into main_imageword (id, label, url) values (1, 'disintermediate', 'https://picsum.photos/seed/yWAz/300/300');
insert into main_imageword (id, label, url) values (2, 'secured line', 'https://picsum.photos/seed/gVtJ/300/300');
insert into main_imageword (id, label, url) values (3, 'human-resource', 'https://picsum.photos/seed/XIcI/300/300');
insert into main_imageword (id, label, url) values (4, 'bottom-line', 'https://picsum.photos/seed/eBFr/300/300');
insert into main_imageword (id, label, url) values (5, 'intranet', 'https://picsum.photos/seed/zlmx/300/300');
insert into main_imageword (id, label, url) values (6, 'circuit', 'https://picsum.photos/seed/kcVf/300/300');
insert into main_imageword (id, label, url) values (7, 'value-added', 'https://picsum.photos/seed/mIyk/300/300');
insert into main_imageword (id, label, url) values (8, '6th generation', 'https://picsum.photos/seed/yWMr/300/300');
insert into main_imageword (id, label, url) values (9, 'User-friendly', 'https://picsum.photos/seed/fqfU/300/300');
insert into main_imageword (id, label, url) values (10, 'fault-tolerant', 'https://picsum.photos/seed/bNWr/300/300');
insert into main_imageword (id, label, url) values (11, 'explicit', 'https://picsum.photos/seed/QCGH/300/300');
insert into main_imageword (id, label, url) values (12, 'fault-tolerant', 'https://picsum.photos/seed/bIvT/300/300');
insert into main_imageword (id, label, url) values (13, 'Automated', 'https://picsum.photos/seed/ZlXF/300/300');
insert into main_imageword (id, label, url) values (14, 'collaboration', 'https://picsum.photos/seed/qKnL/300/300');
insert into main_imageword (id, label, url) values (15, 'emulation', 'https://picsum.photos/seed/cWbu/300/300');
insert into main_imageword (id, label, url) values (16, 'Up-sized', 'https://picsum.photos/seed/lAHc/300/300');
insert into main_imageword (id, label, url) values (17, 'zero defect', 'https://picsum.photos/seed/cDHr/300/300');
insert into main_imageword (id, label, url) values (18, 'internet solution', 'https://picsum.photos/seed/HHvN/300/300');
insert into main_imageword (id, label, url) values (19, 'intermediate', 'https://picsum.photos/seed/VVRN/300/300');
insert into main_imageword (id, label, url) values (20, 'background', 'https://picsum.photos/seed/tybT/300/300');
insert into main_imageword (id, label, url) values (21, 'non-volatile', 'https://picsum.photos/seed/DwJx/300/300');
insert into main_imageword (id, label, url) values (22, 'Total', 'https://picsum.photos/seed/ZrDU/300/300');
insert into main_imageword (id, label, url) values (23, 'Pre-emptive', 'https://picsum.photos/seed/wYTF/300/300');
insert into main_imageword (id, label, url) values (24, 'Mandatory', 'https://picsum.photos/seed/ZYBm/300/300');
insert into main_imageword (id, label, url) values (25, 'next generation', 'https://picsum.photos/seed/hHOj/300/300');
insert into main_imageword (id, label, url) values (26, 'budgetary management', 'https://picsum.photos/seed/TWcE/300/300');
insert into main_imageword (id, label, url) values (27, 'full-range', 'https://picsum.photos/seed/onFI/300/300');
insert into main_imageword (id, label, url) values (28, 'Up-sized', 'https://picsum.photos/seed/CThs/300/300');
insert into main_imageword (id, label, url) values (29, 'flexibility', 'https://picsum.photos/seed/Fkvs/300/300');
insert into main_imageword (id, label, url) values (30, 'interactive', 'https://picsum.photos/seed/RgnF/300/300');
insert into main_imageword (id, label, url) values (31, 'Configurable', 'https://picsum.photos/seed/uvJd/300/300');
insert into main_imageword (id, label, url) values (32, 'Operative', 'https://picsum.photos/seed/WxVT/300/300');
insert into main_imageword (id, label, url) values (33, 'open architecture', 'https://picsum.photos/seed/CqqF/300/300');
insert into main_imageword (id, label, url) values (34, 'solution-oriented', 'https://picsum.photos/seed/NYpe/300/300');
insert into main_imageword (id, label, url) values (35, 'Synchronised', 'https://picsum.photos/seed/BWXF/300/300');
insert into main_imageword (id, label, url) values (36, 'help-desk', 'https://picsum.photos/seed/boCl/300/300');
insert into main_imageword (id, label, url) values (37, 'artificial intelligence', 'https://picsum.photos/seed/LfmG/300/300');
insert into main_imageword (id, label, url) values (38, 'Public-key', 'https://picsum.photos/seed/caJg/300/300');
insert into main_imageword (id, label, url) values (39, 'help-desk', 'https://picsum.photos/seed/YIVC/300/300');
insert into main_imageword (id, label, url) values (40, 'Cross-group', 'https://picsum.photos/seed/tvAb/300/300');
insert into main_imageword (id, label, url) values (41, 'Integrated', 'https://picsum.photos/seed/QWFJ/300/300');
insert into main_imageword (id, label, url) values (42, 'Exclusive', 'https://picsum.photos/seed/wnJY/300/300');
insert into main_imageword (id, label, url) values (43, 'frame', 'https://picsum.photos/seed/aASs/300/300');
insert into main_imageword (id, label, url) values (44, 'Multi-channelled', 'https://picsum.photos/seed/wqHO/300/300');
insert into main_imageword (id, label, url) values (45, 'background', 'https://picsum.photos/seed/nqPN/300/300');
insert into main_imageword (id, label, url) values (46, 'client-server', 'https://picsum.photos/seed/iage/300/300');
insert into main_imageword (id, label, url) values (47, 'neutral', 'https://picsum.photos/seed/sLkn/300/300');
insert into main_imageword (id, label, url) values (48, 'Front-line', 'https://picsum.photos/seed/MNbs/300/300');
insert into main_imageword (id, label, url) values (49, 'grid-enabled', 'https://picsum.photos/seed/wAhB/300/300');
insert into main_imageword (id, label, url) values (50, 'Compatible', 'https://picsum.photos/seed/wpKn/300/300');
insert into main_imageword (id, label, url) values (51, 'De-engineered', 'https://picsum.photos/seed/YzUD/300/300');
insert into main_imageword (id, label, url) values (52, 'encryption', 'https://picsum.photos/seed/ekWH/300/300');
insert into main_imageword (id, label, url) values (53, 'Realigned', 'https://picsum.photos/seed/wCSK/300/300');
insert into main_imageword (id, label, url) values (54, 'flexibility', 'https://picsum.photos/seed/ajQE/300/300');
insert into main_imageword (id, label, url) values (55, 'transitional', 'https://picsum.photos/seed/Wlcy/300/300');
insert into main_imageword (id, label, url) values (56, 'Assimilated', 'https://picsum.photos/seed/fcDp/300/300');
insert into main_imageword (id, label, url) values (57, 'encryption', 'https://picsum.photos/seed/TRYc/300/300');
insert into main_imageword (id, label, url) values (58, 'Secured', 'https://picsum.photos/seed/ptIV/300/300');
insert into main_imageword (id, label, url) values (59, 'Reduced', 'https://picsum.photos/seed/YQxN/300/300');
insert into main_imageword (id, label, url) values (60, 'conglomeration', 'https://picsum.photos/seed/MUAX/300/300');
insert into main_imageword (id, label, url) values (61, 'standardization', 'https://picsum.photos/seed/dpkd/300/300');
insert into main_imageword (id, label, url) values (62, 'Proactive', 'https://picsum.photos/seed/VlQD/300/300');
insert into main_imageword (id, label, url) values (63, 'pricing structure', 'https://picsum.photos/seed/ZRIV/300/300');
insert into main_imageword (id, label, url) values (64, 'focus group', 'https://picsum.photos/seed/TwCb/300/300');
insert into main_imageword (id, label, url) values (65, 'software', 'https://picsum.photos/seed/WEAe/300/300');
insert into main_imageword (id, label, url) values (66, 'zero defect', 'https://picsum.photos/seed/vvYO/300/300');
insert into main_imageword (id, label, url) values (67, 'solution', 'https://picsum.photos/seed/RPUd/300/300');
insert into main_imageword (id, label, url) values (68, 'scalable', 'https://picsum.photos/seed/HmsA/300/300');
insert into main_imageword (id, label, url) values (69, 'groupware', 'https://picsum.photos/seed/FqGc/300/300');
insert into main_imageword (id, label, url) values (70, 'encoding', 'https://picsum.photos/seed/PeQs/300/300');
insert into main_imageword (id, label, url) values (71, 'asynchronous', 'https://picsum.photos/seed/BVWY/300/300');
insert into main_imageword (id, label, url) values (72, 'Automated', 'https://picsum.photos/seed/Jbgn/300/300');
insert into main_imageword (id, label, url) values (73, 'eco-centric', 'https://picsum.photos/seed/RupN/300/300');
insert into main_imageword (id, label, url) values (74, 'radical', 'https://picsum.photos/seed/GAMq/300/300');
insert into main_imageword (id, label, url) values (75, 'heuristic', 'https://picsum.photos/seed/NVwr/300/300');
insert into main_imageword (id, label, url) values (76, 'Synergized', 'https://picsum.photos/seed/eBVm/300/300');
insert into main_imageword (id, label, url) values (77, '24 hour', 'https://picsum.photos/seed/kSvN/300/300');
insert into main_imageword (id, label, url) values (78, 'leading edge', 'https://picsum.photos/seed/MYSI/300/300');
insert into main_imageword (id, label, url) values (79, 'next generation', 'https://picsum.photos/seed/lFrA/300/300');
insert into main_imageword (id, label, url) values (80, 'foreground', 'https://picsum.photos/seed/MJTj/300/300');
insert into main_imageword (id, label, url) values (81, 'pricing structure', 'https://picsum.photos/seed/IjXo/300/300');
insert into main_imageword (id, label, url) values (82, 'help-desk', 'https://picsum.photos/seed/UyKI/300/300');
insert into main_imageword (id, label, url) values (83, 'framework', 'https://picsum.photos/seed/CeVt/300/300');
insert into main_imageword (id, label, url) values (84, 'Business-focused', 'https://picsum.photos/seed/YmnR/300/300');
insert into main_imageword (id, label, url) values (85, 'Inverse', 'https://picsum.photos/seed/wztQ/300/300');
insert into main_imageword (id, label, url) values (86, 'Stand-alone', 'https://picsum.photos/seed/BKeS/300/300');
insert into main_imageword (id, label, url) values (87, 'Devolved', 'https://picsum.photos/seed/skju/300/300');
insert into main_imageword (id, label, url) values (88, 'concept', 'https://picsum.photos/seed/nkXh/300/300');
insert into main_imageword (id, label, url) values (89, 'Persevering', 'https://picsum.photos/seed/DeWp/300/300');
insert into main_imageword (id, label, url) values (90, 'stable', 'https://picsum.photos/seed/BwGH/300/300');
insert into main_imageword (id, label, url) values (91, 'Assimilated', 'https://picsum.photos/seed/EjTk/300/300');
insert into main_imageword (id, label, url) values (92, 'moderator', 'https://picsum.photos/seed/gWCm/300/300');
insert into main_imageword (id, label, url) values (93, 'Open-source', 'https://picsum.photos/seed/VeMs/300/300');
insert into main_imageword (id, label, url) values (94, 'optimal', 'https://picsum.photos/seed/FecR/300/300');
insert into main_imageword (id, label, url) values (95, 'attitude-oriented', 'https://picsum.photos/seed/YBad/300/300');
insert into main_imageword (id, label, url) values (96, 'systematic', 'https://picsum.photos/seed/zgcE/300/300');
insert into main_imageword (id, label, url) values (97, 'knowledge base', 'https://picsum.photos/seed/CSjV/300/300');
insert into main_imageword (id, label, url) values (98, 'Multi-tiered', 'https://picsum.photos/seed/HsmP/300/300');
insert into main_imageword (id, label, url) values (99, 'Front-line', 'https://picsum.photos/seed/Xokl/300/300');
insert into main_imageword (id, label, url) values (100, 'software', 'https://picsum.photos/seed/pAsn/300/300');
